### ISSUE TITLE
Data Type Buffer

### ISSUE THREAD

**Issue by jannicars** [phretaddin/schemapack#10]
What do you think about adding a new data type buffer where you're able to write a buffer to it? For example for uploading a picture via binary data. Of course I could use the binary message with websockets instead but I'd like to add more informations to the message like fileName (String), fileSize (UINT32), fileData (Buffer).

**Comment by phretaddin** [comment]
Sounds like a good idea! Do you want to submit a pull request or should I code it?

**Comment by jannicars** [comment]
https://github.com/phretaddin/schemapack/pull/12 Here we go

**Comment by phretaddin** [comment]
Responded to your pull request
