### ISSUE TITLE
Is there anyway to use schemapack without browserfy?

### ISSUE THREAD

**Issue by Jared-Sprague** [phretaddin/schemapack#13]
Hello!

We really want to use this in our current project but using browserfy is not an option.   Is there a way to use schemapack on the client without having to build a bundle.js?  Can we include some dependencies in script tags directly to make it work?

The server is no problem, just the client.

Thanks!

**Comment by phretaddin** [comment]
Hmm, there might be a way, but none that I'm immediately aware of.

The client needs the `buffer` dependency as it allows the code to work on both the server and client without modification (as the `buffer` dependency has the exact same API as the node server `Buffer`).

I'm a bit curious why you cannot use browserify. You just need to execute it once to generate a bundle to include `schemapack` with `buffer`. Would it help if I included a built version in the repo for client use?

**Comment by jannicars** [comment]
Just build it once via browserify and add this code to your project then. This is also how I will do it.

And yep, a ready-to-use browser version would be amazing.

**Comment by Jared-Sprague** [comment]
@phretaddin Thanks for the quick response!  We don't use broserfy because we have a 'no-build' policy,  we like to be able to make changes to our client side code and see them without out an additional build step.

We could manually browserfy schemapack as @jannicars mentioned above, but that means we would have to do that whenever it's updated.

A pre-built client side library with a schemapack global would be super awesome!  So we can just include on the client:

```
<script src="schemapack.js"><script>
<script>
var playerSchema = schemapack.build({
    health: "varuint",
    jumping: "boolean",
    position: [ "int16" ],
    attributes: { str: 'uint8', agi: 'uint8', int: 'uint8' }
});
</script>
```

That would stay up-to-date with your current release process.

**Comment by jannicars** [comment]
Check out the newest commit: https://github.com/phretaddin/schemapack/commit/621b82f654400af3a795bd9018d0ec20992fcb63

**Comment by phretaddin** [comment]
Yup, just added this. Let me know if this works for you.

**Comment by Jared-Sprague** [comment]
wow that was fast! thanks! I'll try it out now.

**Comment by Jared-Sprague** [comment]
@phretaddin Worked great!  Would it be possible to include a non-minified version in the build directory?  For development sometimes it's nice to use non-minified for debugging, and minified for production.

**Comment by phretaddin** [comment]
Sure, one sec.

**Comment by Jared-Sprague** [comment]
thanks!
