### ISSUE TITLE
Socket.IO Integration

### ISSUE THREAD

**Issue by jannicars** [phretaddin/schemapack#14]
Heya,

Did you try it with Socket.IO already? I'm in the progress of adding this to my Socket.IO project.

On the client side I do the following:
```javascript
var player = {
    health: 4000,
    jumping: false,
    position: [ -540, 343, 1201 ],
    attributes: { str: 87, agi: 42, int: 22 }
}
socket.emit(300, playerSchema.encode(player))
```

Server side:
```javascript
socket.on(300, function(message) {
    if(message.type !== 'Buffer') {
        return
    }
		
    var player = playerSchema.decode(new Buffer(message.data))
    console.log(player)
})
```

How the message gets transmitted:
`
42[300, {type: "Buffer", data: [42, 22, 87, 160, 31, 0, 3, 253, 228, 1, 87, 4, 177]}]
`

I didn't find a setting yet to switch to binary completely. (I assume Socket.IO doesn't support it due to the fallbacks to other transports. I may switch to a websocket solution only later.)

Let's move to this line:
```javascript
var player = playerSchema.decode(new Buffer(message.data))
```

Wouldn't it better if Schemapack transforms an array into a buffer?

**Comment by phretaddin** [comment]
Do you mean changing [this line](https://github.com/phretaddin/schemapack/blob/master/schemapack.js#L392) to something that includes a check for arrays and if so, creates a buffer from them?

That could be added, but it doesn't seem like there's much of a point to using `schemapack` over WebSockets if your websocket library is copying your packets to arrays. Perhaps try using `Primus`/`uws`/`ws` or taking a [look at this](http://socket.io/blog/introducing-socket-io-1-0/#binary)?

**Comment by jannicars** [comment]
Yeah, I changed this line already to the following:

```javascript
var bufferWrapper = ((typeof buffer === 'object' && !Buffer.isBuffer(buffer)) || buffer instanceof ArrayBuffer) ? bufferFrom(buffer) : buffer;
```

Right now I'm trying to figure out how to change to binary transport with Socket.IO completely. No success so far and yep, you're right, with the fake binary via array it would add even more overhead than without Schemapack. 

Will keep you updated until I found out more.

**Comment by jannicars** [comment]
Just figured out that the message from the server to the client is binary already. Now I'm trying to send binary messages from the client to the server.

**Comment by phretaddin** [comment]
Yeah, I probably wouldn't use socket.io. It seems slow and it doesn't look like they even still care enough at this point to get their travis tests to pass, based on their github commit history. I ended up going with [Primus](https://github.com/primus/primus) for my application because it provided a uniform API over all the websocket libraries and lets you swap them out with one line. Either that or use [websockets](https://github.com/websockets/ws) or [uws](https://www.npmjs.com/package/uws). The former is more stable and the latter is faster but still in active development, although looks like it's decent enough for use at this point.

**Comment by jannicars** [comment]
I made it now!

I convinced Socket.IO to send the both messages completely in binary.
http://image.prntscr.com/image/d978477cc70041b88e06a83514f382f4.png
But the drawback is here, that the Socket.IO protocol here seems to add a message to each binary message. I didn't google yet what it does exactly.

For all others: To send a binary message in Socket.IO from the browser to the server, you need to make sure that the input is an ArrayBuffer. I used this little method to transform an Array into an ArrayBuffer:

``` javascript
function arrayToArrayBuffer(array) {
    var ab = new ArrayBuffer(array.length)
    var view = new Uint8Array(ab)
        for (var i = 0; i < array.length; ++i) {
            view[i] = array[i]
        }
    return ab
}
```

Now I'm trying to get rid of this message from Socket.IO but I'm not sure if this is possible.

**Comment by phretaddin** [comment]
Think we should just change that `bufferWrapper` line to this?

`var bufferWrapper = Buffer.isBuffer(buffer) ? buffer : bufferFrom(buffer);`

**Comment by jannicars** [comment]
Yeah, I'd suggest that too.

Also I found out that those additional messages from Socket.IO are binary fallback messages in case your browser doesn't support binary messages. They always stay small like this so I think I'm okay with this.

Next week I will change some messages to Schemapack, will push it out to production and see how it performs. I love the idea that I can describe the schema so easily and I know what I can expect + it is so lightweight how it should. I already changed all the event names to integers instead of string names. This already safes a lot of bandwitdth.

I think we can close this issue. I made it working how it should via Socket.IO (Including uWS), messages are sent via binary (and this additional fallback message) and I'm happy with the result for now. I may change someday the realtime framework.

**Comment by phretaddin** [comment]
Good stuff.

Also, if you're not already doing this, for my app I made a huge dictionary of packet types, so you can emit readable numbers.

var packets = {
  "packetOne": 1,
  "packetTwo": 2,
  "packetThree": 3
};

Then do `socket.emit(packets.packetOne, data);`

Makes it a lot easier to develop because you know what message type each packet is, and it is still bandwidth efficient because the key values are just integers.

**Comment by jannicars** [comment]
Yeah, I do this exactly the same. Thanks for confirming that my idea wasn't that bad when I started with it like that!

I'm still thinking about the ArrayToArrayBuffer method. Would that be wrong if we add this to Schemapack as well or don't you see it in there? So I don't need to wrap it all the time.

**Comment by phretaddin** [comment]
I think once you use a better websocket library you won't need that. I haven't needed anything like that at least for my app.

**Comment by jannicars** [comment]
Okay, I will close this issue then. Thank you!
