### ISSUE TITLE
No mentions to (not object-wrapped) array serializations

### ISSUE THREAD

**Issue by castarco** [phretaddin/schemapack#3]
SchemaPack is directly compared with some serialization formats like JSON and MessagePack. Both of them have the ability to directly serialize arrays, without the need of wrapping them into "objects", in the SchemaPack documentation there is no info about how to directly serialize arrays without having to wrap them in objects.

Is this possible? If no, maybe it should be convenient to explain it to make easier for other programmers which limitations has this serialization format.

**Comment by phretaddin** [comment]
Do you mean something like this? https://github.com/phretaddin/schemapack/blob/master/README.md#add-type-aliases

You can directly serialize arrays. Maybe I should make a larger point of it. I kinda just included it in another example.

**Comment by phretaddin** [comment]
Updated the readme to better inform of this feature's existence.
