### ISSUE TITLE
support for big & little endian

### ISSUE THREAD

**Issue by ajoslin103** [phretaddin/schemapack#7]
is support for big & little endian planned ?

**Comment by phretaddin** [comment]
Not at the moment. I basically just picked big endian on a whim. It should be trivial to change or add on a fork if you want, though. Just change all the `readXBE` and `writeXBE` functions to `LE` if you prefer little endian, or create a function that swaps them out.

https://github.com/phretaddin/schemapack/blob/master/schemapack.js#L74
https://github.com/phretaddin/schemapack/blob/master/schemapack.js#L89

**Comment by ajoslin103** [comment]
I don't need it at the moment, since it's BE to start

I'll leave that change to someone else
